name: robs_sport_club
description: "A comprehensive app for managing RÃ˜BS Sport Club activities."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  http: ^1.2.2
  shared_preferences: ^2.1.1
  jwt_decoder: ^2.0.1
  form_field_validator: ^1.1.0
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.1

flutter:
  uses-material-design: true
